# Generated by Django 4.2.10 on 2024-02-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leave', '0002_remove_leaverequest_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
